// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urizmucmwuuczpxhzxce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaXptdWNtd3V1Y3pweGh6eGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjEwMTcsImV4cCI6MjA3MzMzNzAxN30.JKJ07rLnxLwximz69n5gUx_wvw6_7FYRtFxHGumvqT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});